architecture: "BasicUNet"
kernel_size: 5

only_pred_local: True
local_features: ["permanent_water"]
context_features: ["sentinel1", "sentinel2", "dem", "precipitation", "permanent_water", "soil_bulk_density", "soil_moisture_one_day", "soil_class", "land_cover"]

exclude_scales: ["local"]

class_weights: [0, 0.1, 1.9]
use_scheduler: False
learning_rate: 0.0001
dropout: 0.1
weight_decay: 0.0001
batch_size: 32
number_workers: 8
number_epochs: 100

save_model_on_epoch: 10
compute_metrics_on_epoch: 10

data_subset_file: "only_patches_no_flood_data_subset"