name: flood-prediction
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - scikit-image
  - scikit-learn
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.6.0+cu126
    - torchvision==0.21.0+cu126
    - torchaudio==2.6.0+cu126
    - scipy
    - timm
    - segmentation_models_pytorch
    - tqdm
    - torchinfo
    - torchmetrics
    - tifffile
    - geopandas