architecture: "test"

features: ["dem", "permanent_water", "soil_moisture_one_week", "soil_moisture_one_day", "soil_class", "soil_bulk_density"]

separate_flood_trace_label: False

number_epochs: 3
learning_rate: 0.001
weight_decay: 0

batch_size: 32
number_workers: 20

save_model_on_epoch: 3
calculate_metrics_on_epoch: 3