architecture: "test"

features: ["dem"]

separate_flood_trace_label: False

number_epochs: 3
learning_rate: 0.001
weight_decay: 0

batch_size: 32
number_workers: 32

save_model_on_epoch: 0
calculate_metrics_on_epoch: 0

data_subset_file: "testing_data_subset"